---
title: "DTA_L15_Plotly"
author: "Joy Hsu"
date: "10/23/2018"
output: html_document
---

### Lecture

* Dashboards
    * Ex. fitbit, investing platform, finances
    * most useful in the context of changing data. Data is changing, but structure of the platform is static
    
* flexdashboard
    * works with shiny
    * 

### 0. Setup

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

Install airbnb dataset, cleanup
```{r}
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating), 
         boro == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)  %>% 
  sample_n(5000)
```

# 1. Plotly scatterplot

* scatterplot of nyc airbnb rentals, longitude and latitude
* interactivity

```{r}
#mutate step - 
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
```

